# Generated by Django 4.2.14 on 2024-08-30 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('contacts', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='recruit_photos/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='recruit_pdfs/')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('position_applied', models.CharField(max_length=100)),
                ('interview_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('hiring_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('hiring_date', models.DateField(blank=True, null=True)),
                ('progress_stage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_stage', models.IntegerField(default=0)),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.recruit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('screening_date', models.DateField()),
                ('recruit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.recruit')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_name', models.CharField(max_length=100, null=True)),
                ('bank_account_number', models.CharField(max_length=50, null=True)),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('gsis_contribution', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sss_contribution', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('philhealth_contribution', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pagibig_contribution', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('loan_cash', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
            ],
        ),
        migrations.CreateModel(
            name='FinalInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=False)),
                ('manager_name', models.CharField(max_length=255)),
                ('interview_date', models.DateField()),
                ('recruit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_interviews', to='users.recruit')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_accounts', models.TextField(blank=True, max_length=100, null=True)),
                ('additional_social_media_accounts', models.CharField(blank=True, max_length=100, null=True)),
                ('current_address', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_addresses', models.TextField(blank=True, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_address', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_address', models.CharField(blank=True, max_length=255, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_employers', models.TextField(blank=True, null=True)),
                ('job_titles_responsibilities', models.TextField(blank=True, null=True)),
                ('dates_of_employment', models.CharField(blank=True, max_length=255, null=True)),
                ('reasons_for_leaving', models.TextField(blank=True, null=True)),
                ('supervisor_information', models.TextField(blank=True, null=True)),
                ('has_criminal_record', models.BooleanField(default=False)),
                ('criminal_record_details', models.TextField(blank=True, null=True)),
                ('recruit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.recruit')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('working_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.employee')),
            ],
        ),
    ]
