# Generated by Django 4.2.14 on 2024-08-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_payrollaccount_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollaccount',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
