# Generated by Django 4.2.14 on 2024-08-31 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_payrollaccount_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='id',
            new_name='employee_id',
        ),
    ]
