# Generated by Django 4.2.14 on 2024-08-31 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_id_employee_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollaccount',
            old_name='loan_cash',
            new_name='gross_pay',
        ),
        migrations.RemoveField(
            model_name='payrollaccount',
            name='bank_account_name',
        ),
        migrations.RemoveField(
            model_name='payrollaccount',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='payrollaccount',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='payrollaccount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payrollaccount',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='payrollaccount',
            name='gsis_account',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payrollaccount',
            name='overtime_pay',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payrollaccount',
            name='pagibig_account',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payrollaccount',
            name='philhealth_account',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payrollaccount',
            name='sss_account',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_account', to='users.employee'),
        ),
    ]
