# Generated by Django 4.2.14 on 2024-08-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_overtime_pay_payrollaccount_allowance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollaccount',
            name='bank_account',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='basic_pay',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='gross_pay',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='gsis_account',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='gsis_contribution',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='over_time_pay',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='pag_ibig_account',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='pag_ibig_contribution',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='phil_health_account',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='phil_health_contribution',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='sss_account',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='sss_contribution',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
