# Generated by Django 4.2.14 on 2024-08-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_payrollaccount_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollaccount',
            name='allowance',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='basic_pay',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='gross_pay',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='gsis_account',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='gsis_contribution',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='over_time_pay',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='pag_ibig_account',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='pag_ibig_contribution',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='phil_health_account',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='phil_health_contribution',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='sss_account',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='sss_contribution',
            field=models.CharField(max_length=15),
        ),
    ]
