# Generated by Django 4.2.14 on 2024-08-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_payrollaccount_allowance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollaccount',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
