# Generated by Django 4.2.14 on 2024-08-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_payrollaccount_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollaccount',
            name='department',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='position',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
