# Generated by Django 4.2.14 on 2024-08-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_payrollaccount_gross_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollaccount',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='basic_pay',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='gsis_account',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='gsis_contribution',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='over_time_pay',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='pag_ibig_account',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='pag_ibig_contribution',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='phil_health_account',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='phil_health_contribution',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='sss_account',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='payrollaccount',
            name='sss_contribution',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
