# Generated by Django 4.2.14 on 2024-09-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_payrollaccount_bank_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('worked_days', models.PositiveIntegerField()),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('over_time_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sss_contribution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gsis_contribution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phil_health_contribution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pag_ibig_contribution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_deductions', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
